name: CI Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  #Test's job
  build-and-analyze:
    name: Build, Test and Analyze
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: bank_test
          MYSQL_USER: bankapp
          MYSQL_PASSWORD: strongPassword254!$
          MYSQL_ROOT_PASSWORD: strongRootPassword854!!
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      #Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      #Set up SonarCloud cache
      - name: Cache SonarCloud packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      #Analyze project with SonarCloud
      - name: Analyze with SonarCloud
        #Enviroment variables
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DB_URL: jdbc:mysql://localhost:3306/bank_test
          DB_USERNAME: bankapp
          DB_PASSWORD: strongPassword254!$
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage